# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nll_Rcpp <- function(allprobs, gamma, delta, T_y) {
    .Call(`_PHSMM_nll_Rcpp`, allprobs, gamma, delta, T_y)
}

